STRING OPERATIONS IN PANDAS

In [7]:
import pandas as pd

In [8]:
employee_df = pd.DataFrame({
     "Employee" : [" Rahul " , "PRIYA" , "amit" , "Sneha"],
     "Email" : ["Rahul@Company.COM","PRIYA@Company.COM","amit@Company.COM","Sneha@Company.COM"]
})

employee_df

  Employee              Email
0   Rahul   Rahul@Company.COM
1    PRIYA  PRIYA@Company.COM
2     amit   amit@Company.COM
3    Sneha  Sneha@Company.COM

In [9]:
# Convert name to lowercase
employee_df["Employee"].str.lower()

0     rahul
1      priya
2       amit
3      sneha
Name: Employee, dtype: object

In [10]:
# Convert name to uppercase
employee_df["Employee"].str.upper()

0     RAHUL
1      PRIYA
2       AMIT
3      SNEHA
Name: Employee, dtype: object

In [11]:
# Convert name in title
employee_df["Employee"].str.title()

0     Rahul
1      Priya
2       Amit
3      Sneha
Name: Employee, dtype: object

In [12]:
# Removes Extra spaces from name
employee_df["Employee"].str.strip()

0    Rahul
1    PRIYA
2     amit
3    Sneha
Name: Employee, dtype: object

CONTAINS()

In [13]:
# find name which contains a
employee_df["Employee"].str.contains("a")

0     True
1    False
2     True
3     True
Name: Employee, dtype: bool

In [14]:
# find emails contains company
employee_df["Email"].str.contains("Company")

0    True
1    True
2    True
3    True
Name: Email, dtype: bool

In [17]:
# Ignore the case sensitivity
employee_df["Email"].str.contains(
     "company",
     case=False
)

0    True
1    True
2    True
3    True
Name: Email, dtype: bool

STARTWITH() , ENDSWITH() , REPLACE() , SPLIT()

In [19]:
# Checks the string startwith....
employee_df["Employee"].str.startswith("R")
# it shows all false because the " Rahul " contains extra spaces

0    False
1    False
2    False
3    False
Name: Employee, dtype: bool

In [22]:
# Checks string endswith...
employee_df["Email"].str.endswith(".COM")

0    True
1    True
2    True
3    True
Name: Email, dtype: bool

In [23]:
# Replace the part of string
employee_df["Email"].str.replace(
     "Company",
     "Google"
)

0    Rahul@Google.COM
1    PRIYA@Google.COM
2     amit@Google.COM
3    Sneha@Google.COM
Name: Email, dtype: object

In [24]:
# Replace the employee name
employee_df["Employee"].str.replace(
     "Rahul",
     "Rohit"
)

0     Rohit
1      PRIYA
2       amit
3      Sneha
Name: Employee, dtype: object

In [39]:
players_df = pd.DataFrame({
     "Full Name" : [
          "Rohit Sharma",
          "Harmanpreet Kaur",
          "Virat Kohli",
          "Smriti Mandhana"
     ]
})

In [43]:
# use to split the strin
players_df["Full Name"].str.split(" ")

0        [Rohit, Sharma]
1    [Harmanpreet, Kaur]
2         [Virat, Kohli]
3     [Smriti, Mandhana]
Name: Full Name, dtype: object

In [41]:
# create the first name column and access the first name from full name
players_df["First Name"] = players_df["Full Name"].str.split().str[0]

players_df

          Full Name   First Name
0      Rohit Sharma        Rohit
1  Harmanpreet Kaur  Harmanpreet
2       Virat Kohli        Virat
3   Smriti Mandhana       Smriti

In [42]:
players_df["Last Name"] = players_df["Full Name"] .str.split().str[1]

players_df

          Full Name   First Name Last Name
0      Rohit Sharma        Rohit    Sharma
1  Harmanpreet Kaur  Harmanpreet      Kaur
2       Virat Kohli        Virat     Kohli
3   Smriti Mandhana       Smriti  Mandhana