# DAY 26 : ADVANCED PANDAS I

In [2]:
import pandas as pd

In [3]:
# Orders
orders = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104],
    "Customer_ID": ["C01", "C02", "C01", "C04"],
    "Sales": [500, 700, 300, 900]
})

orders

   Order_ID Customer_ID  Sales
0       101         C01    500
1       102         C02    700
2       103         C01    300
3       104         C04    900

In [4]:
# Customers
customers = pd.DataFrame({
    "Customer_ID": ["C01", "C02", "C03"],
    "Customer_Name": ["Rahul", "Amit", "Sneha"],
    "Segment": ["Consumer", "Corporate", "Consumer"]
})

customers

  Customer_ID Customer_Name    Segment
0         C01         Rahul   Consumer
1         C02          Amit  Corporate
2         C03         Sneha   Consumer