ADVANCED REAL WORLD DATA ANALYSIS

In [2]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_12632\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.shape

(180519, 31)

In [4]:
df.columns

Index(['Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Department Name', 'Market',
       'Order Country', 'order date (DateOrders)', 'Order Id',
       'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Benefit per order           180519 non-null  float64
 1   Sales per customer          180519 non-null  float64
 2   Delivery Status             180519 non-null  object
 3   Late_delivery_risk          180519 non-null  int64
 4   Category Name               180519 non-null  object
 5   Customer City               180519 non-null  object
 6   Customer Country            180519 non-null  object
 7   Customer Fname              180519 non-null  object
 8   Customer Id                 180519 non-null  int64
 9   Customer Lname              180511 non-null  object
 10  Customer Segment            180519 non-null  object
 11  Customer State              180519 non-null  object
 12  Department Name             180519 non-null  object
 13  Market                      180519 non-null  object
 14  Order Country               180519 non-null  object
 15  order date (DateOrders)     180519 non-null  object
 16  Order Id                    180519 non-null  int64
 17  Order Item Discount         180519 non-null  float64
 18  Order Item Discount Rate    180519 non-null  float64
 19  Order Item Product Price    180519 non-null  float64
 20  Order Item Profit Ratio     180519 non-null  float64
 21  Order Item Quantity         180519 non-null  int64
 22  Sales                       180519 non-null  float64
 23  Order Item Total            180519 non-null  float64
 24  Order Profit Per Order      180519 non-null  float64
 25  Order Region                180519 non-null  object
 26  Order State                 180519 non-null  object
 27  Order Status                180519 non-null  object
 28  Product Name                180519 non-null  object
 29  shipping date (DateOrders)  180519 non-null  object
 30  Shipping Mode               180519 non-null  object
dtypes: float64(9), int64(4), object(18)
memory usage: 42.7+ MB

In [6]:
df.describe()

,Benefit per order,Sales per customer,Late_delivery_risk,Customer Id,Order Id,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,21.974989,183.107609,0.548291,6691.379495,36221.894903,20.664741,0.101668,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989
std,104.433526,120.043670,0.497664,4162.918106,21045.379569,21.800901,0.070415,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526
min,-4274.979980,7.490000,0.000000,1.000000,1.000000,0.000000,0.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980
25%,7.000000,104.379997,0.000000,3258.500000,18057.000000,5.400000,0.040000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000
50%,31.520000,163.990005,1.000000,6457.000000,36140.000000,14.000000,0.100000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000
75%,64.800003,247.399994,1.000000,9779.000000,54144.000000,29.990000,0.160000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003
max,911.799988,1939.989990,1.000000,20757.000000,77204.000000,500.000000,0.250000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988

DATA QUALITY ANALYSIS

In [7]:
df.isnull().sum()

Benefit per order             0
Sales per customer            0
Delivery Status               0
Late_delivery_risk            0
Category Name                 0
Customer City                 0
Customer Country              0
Customer Fname                0
Customer Id                   0
Customer Lname                8
Customer Segment              0
Customer State                0
Department Name               0
Market                        0
Order Country                 0
order date (DateOrders)       0
Order Id                      0
Order Item Discount           0
Order Item Discount Rate      0
Order Item Product Price      0
Order Item Profit Ratio       0
Order Item Quantity           0
Sales                         0
Order Item Total              0
Order Profit Per Order        0
Order Region                  0
Order State                   0
Order Status                  0
Product Name                  0
shipping date (DateOrders)    0
Shipping Mode                 0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df["Delivery Status"].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [10]:
df["Late_delivery_risk"].value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [11]:
df["Order Status"].value_counts()

Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

In [14]:
df[["order date (DateOrders)" ,"shipping date (DateOrders)"]].head()

  order date (DateOrders) shipping date (DateOrders)
0         1/31/2018 22:56           02-03-2018 22:56
1         1/13/2018 12:27            1/18/2018 12:27
2         1/13/2018 12:06            1/17/2018 12:06
3         1/13/2018 11:45            1/16/2018 11:45
4         1/13/2018 11:24            1/15/2018 11:24

In [20]:
df["order date (DateOrders)"] = pd.to_datetime(
    df["order date (DateOrders)"] ,
    format="mixed"
)

df["shipping date (DateOrders)"] = pd.to_datetime(
    df["shipping date (DateOrders)"],
    format="mixed"
)

In [21]:
df[["order date (DateOrders)" ,"shipping date (DateOrders)"]].head()

  order date (DateOrders) shipping date (DateOrders)
0     2018-01-31 22:56:00        2018-02-03 22:56:00
1     2018-01-13 12:27:00        2018-01-18 12:27:00
2     2018-01-13 12:06:00        2018-01-17 12:06:00
3     2018-01-13 11:45:00        2018-01-16 11:45:00
4     2018-01-13 11:24:00        2018-01-15 11:24:00

In [23]:
# Date features
df["Order Year"] = df["order date (DateOrders)"].dt.year
df["Order Month"] = df["order date (DateOrders)"].dt.month
df["Order Month Name"] = df["order date (DateOrders)"].dt.month_name()
df["Order Day Name"] = df["order date (DateOrders)"].dt.day_name()

In [26]:
df[[
      "order date (DateOrders)",
          "Order Year",
          "Order Month",
          "Order Month Name",
          "Order Day Name"
]].head()

,order date (DateOrders),Order Year,Order Month,Order Month Name,Order Day Name
0,2018-01-31 22:56:00,2018,1,January,Wednesday
1,2018-01-13 12:27:00,2018,1,January,Saturday
2,2018-01-13 12:06:00,2018,1,January,Saturday
3,2018-01-13 11:45:00,2018,1,January,Saturday
4,2018-01-13 11:24:00,2018,1,January,Saturday