MINI PROJECT 06 : ONLINE RETAIL ANALYTICS

In [2]:
import pandas as pd
import numpy as np

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_19964\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
excel_file = pd.ExcelFile("online_retail_II.xlsx")
excel_file.sheet_names

['Year 2009-2010', 'Year 2010-2011']

LOAD THE DATASET

In [4]:
df_2009 = pd.read_excel("online_retail_II.xlsx" , sheet_name='Year 2009-2010')
df_2010 = pd.read_excel("online_retail_II.xlsx" , sheet_name='Year 2010-2011')

In [5]:
df_2009.shape

(525461, 8)

In [6]:
df_2010.shape

(541910, 8)

In [7]:
df = pd.concat([df_2009 , df_2010] , ignore_index=True)
df.shape

(1067371, 8)

BASIC DATASET EXPLORATION

In [8]:
df.shape

(1067371, 8)

In [9]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [10]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [11]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [13]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,1.067371e+06,1067371,1.067371e+06,824364.000000
mean,9.938898e+00,2011-01-02 21:13:55.394028544,4.649388e+00,15324.638504
min,-8.099500e+04,2009-12-01 07:45:00,-5.359436e+04,12346.000000
25%,1.000000e+00,2010-07-09 09:46:00,1.250000e+00,13975.000000
50%,3.000000e+00,2010-12-07 15:28:00,2.100000e+00,15255.000000
75%,1.000000e+01,2011-07-22 10:23:00,4.150000e+00,16797.000000
max,8.099500e+04,2011-12-09 12:50:00,3.897000e+04,18287.000000
std,1.727058e+02,NaN,1.235531e+02,1697.464450

DATA QUALITY ANALYSIS

In [14]:
# missing values
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [15]:
# duplicate records
df.duplicated().sum()

34335

In [16]:
#Unique values
df["StockCode"].nunique()

5305

In [17]:
df["Customer ID"].nunique()

5942

In [18]:
df["Country"].nunique()

43

In [19]:
# Transaction Types
df["Quantity"].value_counts().head(10)

Quantity
1     294346
2     159960
12    121745
6      85299
3      72638
4      72382
24     47036
10     40956
8      25819
5      23165
Name: count, dtype: int64

In [20]:
df["Invoice"].astype(str).str.startswith("C").value_counts()

Invoice
False    1047877
True       19494
Name: count, dtype: int64

In [21]:
#Identify negative quantities
df[df["Quantity"] < 0 ].shape

(22950, 8)

In [22]:
df[df["Price"] < 0].shape

(5, 8)

In [23]:
df[df["Quantity"] < 0 ].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [24]:
# Inspect negative prices
df[df["Price"] < 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [25]:
# Create a clean working DataFrame
clean_df = df[df["Price"] >= 0 ].copy()
clean_df.shape

(1067366, 8)

In [26]:
clean_df["Price"].min()

0.0

In [27]:
# Check duplicates in clean_df
clean_df.duplicated().sum()

34335

In [28]:
clean_df[clean_df.duplicated(keep=False)].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

In [29]:
#Remove duplicates
clean_df = clean_df.drop_duplicates()
clean_df.shape

(1033031, 8)

In [30]:
clean_df.duplicated().sum()

0

In [31]:
# Missing values
clean_df.isnull().sum()

Invoice             0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
Price               0
Customer ID    235146
Country             0
dtype: int64

In [32]:
clean_df[clean_df["Description"].isnull()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [33]:
clean_df[clean_df["Customer ID"].isnull()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom

HANDLE MISSING VALUES

In [34]:
clean_df["Description"] = clean_df["Description"].fillna("Unknown Product")
clean_df["Description"].isnull().sum()

0

Create Transaction Type

In [37]:
clean_df["Transaction Type"] = np.where(
     clean_df["Invoice"].astype(str).str.startswith("C") , 
     "Cancellation" ,
     "Sale"
)
clean_df["Transaction Type"].value_counts()

Transaction Type
Sale            1013927
Cancellation      19104
Name: count, dtype: int64

In [38]:
# create revenue
clean_df["Revenue"] = clean_df["Quantity"] * clean_df["Price"]
clean_df[["Quantity" , "Price" , "Revenue"]]

         Quantity  Price  Revenue
0              12   6.95    83.40
1              12   6.75    81.00
2              12   6.75    81.00
3              48   2.10   100.80
4              24   1.25    30.00
...           ...    ...      ...
1067366         6   2.10    12.60
1067367         4   4.15    16.60
1067368         4   4.15    16.60
1067369         3   4.95    14.85
1067370         1  18.00    18.00

[1033031 rows x 3 columns]

In [39]:
# Create Date feature
clean_df["Year"] = clean_df["InvoiceDate"].dt.year

In [40]:
clean_df["Month"] = clean_df["InvoiceDate"].dt.month

In [45]:
clean_df["Month Name"] = clean_df["InvoiceDate"].dt.month_name()

In [46]:
clean_df["Day Name"] = clean_df["InvoiceDate"].dt.day_name()

In [47]:
clean_df[["Year" , "Month" , "Month Name" , "Day Name"]].head()

   Year  Month Month Name Day Name
0  2009     12   December  Tuesday
1  2009     12   December  Tuesday
2  2009     12   December  Tuesday
3  2009     12   December  Tuesday
4  2009     12   December  Tuesday

In [48]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1033031 entries, 0 to 1067370
Data columns (total 15 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Invoice           1033031 non-null  object
 1   StockCode         1033031 non-null  object
 2   Description       1033031 non-null  object
 3   Quantity          1033031 non-null  int64
 4   InvoiceDate       1033031 non-null  datetime64[ns]
 5   Price             1033031 non-null  float64
 6   Customer ID       797885 non-null   float64
 7   Country           1033031 non-null  object
 8   Transaction Type  1033031 non-null  object
 9   Revenue           1033031 non-null  float64
 10  Year              1033031 non-null  int32
 11  Month             1033031 non-null  int32
 12  Month_Name        1033031 non-null  object
 13  Month Name        1033031 non-null  object
 14  Day Name          1033031 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(8)
memory usage: 118.2+ MB