MINI PROJECT 05 - SUPPLY CHAIN ANALYTICS

In [2]:
import pandas as pd

In [ ]:
# Load the dataset
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="Latin1")
# Shows top five records
df.head()

,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
0,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,...,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,02-03-2018 22:56,Standard Class
1,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,...,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,1/18/2018 12:27,Standard Class
2,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,...,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,Smart watch,1/17/2018 12:06,Standard Class
3,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,...,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,Smart watch,1/16/2018 11:45,Standard Class
4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,...,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,Smart watch,1/15/2018 11:24,Standard Class

In [11]:
# Shows the total rows and columns
df.shape

(180519, 31)

In [12]:
# Shows the columns names
df.columns

Index(['Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Department Name', 'Market',
       'Order Country', 'order date (DateOrders)', 'Order Id',
       'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [14]:
# Shows the information of all dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Benefit per order           180519 non-null  float64
 1   Sales per customer          180519 non-null  float64
 2   Delivery Status             180519 non-null  object
 3   Late_delivery_risk          180519 non-null  int64
 4   Category Name               180519 non-null  object
 5   Customer City               180519 non-null  object
 6   Customer Country            180519 non-null  object
 7   Customer Fname              180519 non-null  object
 8   Customer Id                 180519 non-null  int64
 9   Customer Lname              180511 non-null  object
 10  Customer Segment            180519 non-null  object
 11  Customer State              180519 non-null  object
 12  Department Name             180519 non-null  object
 13  Market                      180519 non-null  object
 14  Order Country               180519 non-null  object
 15  order date (DateOrders)     180519 non-null  object
 16  Order Id                    180519 non-null  int64
 17  Order Item Discount         180519 non-null  float64
 18  Order Item Discount Rate    180519 non-null  float64
 19  Order Item Product Price    180519 non-null  float64
 20  Order Item Profit Ratio     180519 non-null  float64
 21  Order Item Quantity         180519 non-null  int64
 22  Sales                       180519 non-null  float64
 23  Order Item Total            180519 non-null  float64
 24  Order Profit Per Order      180519 non-null  float64
 25  Order Region                180519 non-null  object
 26  Order State                 180519 non-null  object
 27  Order Status                180519 non-null  object
 28  Product Name                180519 non-null  object
 29  shipping date (DateOrders)  180519 non-null  object
 30  Shipping Mode               180519 non-null  object
dtypes: float64(9), int64(4), object(18)
memory usage: 42.7+ MB

In [15]:
# Shows the all mathematical calculation 
df.describe()

,Benefit per order,Sales per customer,Late_delivery_risk,Customer Id,Order Id,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,21.974989,183.107609,0.548291,6691.379495,36221.894903,20.664741,0.101668,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989
std,104.433526,120.043670,0.497664,4162.918106,21045.379569,21.800901,0.070415,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526
min,-4274.979980,7.490000,0.000000,1.000000,1.000000,0.000000,0.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980
25%,7.000000,104.379997,0.000000,3258.500000,18057.000000,5.400000,0.040000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000
50%,31.520000,163.990005,1.000000,6457.000000,36140.000000,14.000000,0.100000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000
75%,64.800003,247.399994,1.000000,9779.000000,54144.000000,29.990000,0.160000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003
max,911.799988,1939.989990,1.000000,20757.000000,77204.000000,500.000000,0.250000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988