## DAY 24 TIME BASED BUSINESS ANALYSIS

In [1]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_2244\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [ ]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" ,encoding="latin1")
df[[
          "order date (DateOrders)",
          "shipping date (DateOrders)"
]].dtypes

order date (DateOrders)       object
shipping date (DateOrders)    object
dtype: object

In [3]:
df[[
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]].head()

  order date (DateOrders) shipping date (DateOrders)
0         1/31/2018 22:56           02-03-2018 22:56
1         1/13/2018 12:27            1/18/2018 12:27
2         1/13/2018 12:06            1/17/2018 12:06
3         1/13/2018 11:45            1/16/2018 11:45
4         1/13/2018 11:24            1/15/2018 11:24

In [10]:
df["order date (DateOrders)"] = pd.to_datetime(
     df["order date (DateOrders)"] , format="mixed"
)
df["shipping date (DateOrders)"] = pd.to_datetime(
     df["shipping date (DateOrders)"] , format="mixed"
)

In [13]:
df[[
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]].dtypes

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [14]:
df[[
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]].head()

  order date (DateOrders) shipping date (DateOrders)
0     2018-01-31 22:56:00        2018-02-03 22:56:00
1     2018-01-13 12:27:00        2018-01-18 12:27:00
2     2018-01-13 12:06:00        2018-01-17 12:06:00
3     2018-01-13 11:45:00        2018-01-16 11:45:00
4     2018-01-13 11:24:00        2018-01-15 11:24:00