REAL WORLD DATASET EDA

In [3]:
import pandas as pd

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_8160\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
# We use the encoding because pyhon trying to interpret this file as UTF-8, but this byte doesn't represent a valid UTF-8 character
df = pd.read_csv("superstore.csv" , encoding="latin1")
df.head()

,Order ID,Order Date,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11-08-2016,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,CA-2016-152156,11-08-2016,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,CA-2016-138688,06-12-2016,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,US-2015-108966,10-11-2015,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,US-2015-108966,10-11-2015,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [5]:
# checke the shape of dataset
df.shape

(9994, 14)

In [6]:
# check the columns in dataset
df.columns

Index(['Order ID', 'Order Date', 'Customer Name', 'Segment', 'Country', 'City',
       'State', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity',
       'Discount', 'Profit'],
      dtype='object')

In [7]:
# check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Customer Name  9994 non-null   object
 3   Segment        9994 non-null   object
 4   Country        9994 non-null   object
 5   City           9994 non-null   object
 6   State          9994 non-null   object
 7   Region         9994 non-null   object
 8   Category       9994 non-null   object
 9   Sub-Category   9994 non-null   object
 10  Sales          9994 non-null   float64
 11  Quantity       9994 non-null   int64
 12  Discount       9994 non-null   float64
 13  Profit         9994 non-null   float64
dtypes: float64(3), int64(1), object(10)
memory usage: 1.1+ MB

In [8]:
df.describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [9]:
# check the null values in dataset
df.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Region           0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [10]:
# identify any duplicate values in dataset
df.duplicated().sum()

1

In [11]:
# understand the categorial data
df["Category"].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [12]:
df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [13]:
df["Region"].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [14]:
df["Segment"].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [15]:
# inspect the duplicates
df[df.duplicated(keep=False)]

,Order ID,Order Date,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
3405,US-2014-150119,4/23/2014,Laurel Beltran,Home Office,United States,Columbus,Ohio,East,Furniture,Chairs,281.372,2,0.3,-12.0588
3406,US-2014-150119,4/23/2014,Laurel Beltran,Home Office,United States,Columbus,Ohio,East,Furniture,Chairs,281.372,2,0.3,-12.0588

In [16]:
df[df.duplicated(keep=False)].sort_values(
     by = "Order ID"
)

,Order ID,Order Date,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
3405,US-2014-150119,4/23/2014,Laurel Beltran,Home Office,United States,Columbus,Ohio,East,Furniture,Chairs,281.372,2,0.3,-12.0588
3406,US-2014-150119,4/23/2014,Laurel Beltran,Home Office,United States,Columbus,Ohio,East,Furniture,Chairs,281.372,2,0.3,-12.0588

In [17]:
# remove the duplicate
clean_df = df.drop_duplicates().copy()
clean_df.shape

(9993, 14)

In [18]:
clean_df.duplicated().sum()

0

In [19]:
# checks the datatypes
clean_df.dtypes

Order ID          object
Order Date        object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Region            object
Category          object
Sub-Category      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [20]:
clean_df["Order Date"].head()

0    11-08-2016
1    11-08-2016
2    06-12-2016
3    10-11-2015
4    10-11-2015
Name: Order Date, dtype: object

In [21]:
clean_df["Order Date"].dtype

dtype('O')

In [22]:
# convert order date to date datatype
clean_df["Order Date"] = pd.to_datetime(
    clean_df["Order Date"],
    format="mixed"
)

In [23]:
clean_df["Order Date"].dtype

dtype('<M8[ns]')

In [24]:
clean_df["Order Date"].head()

0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: Order Date, dtype: datetime64[ns]

In [25]:
# Extract the date information
clean_df["Year"] = clean_df["Order Date"].dt.year
clean_df["Month"] = clean_df["Order Date"].dt.month
clean_df["Month Name"] = clean_df["Order Date"].dt.month_name()
clean_df["Day Name"] = clean_df["Order Date"].dt.day_name()

In [26]:
clean_df.head()

,Order ID,Order Date,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Year,Month,Month Name,Day Name
0,CA-2016-152156,2016-11-08,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,2016,11,November,Tuesday
1,CA-2016-152156,2016-11-08,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,219.5820,2016,11,November,Tuesday
2,CA-2016-138688,2016-06-12,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,2016,6,June,Sunday
3,US-2015-108966,2015-10-11,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,0.45,-383.0310,2015,10,October,Sunday
4,US-2015-108966,2015-10-11,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,2015,10,October,Sunday

BUSINESS ANALYSIS

In [27]:
# yearly highest sales
yearly_sales = clean_df.groupby("Year")["Sales"].sum()
yearly_sales

Year
2014    483966.1261
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64

In [28]:
yearly_sales.idxmax(),yearly_sales.max()

(2017, 733215.2552)

In [32]:
# monthly highest sales
monthly_sales = clean_df.groupby(
     "Month Name"

)["Sales"].sum()
monthly_sales

Month Name
April        137480.7566
August       159044.0630
December     325293.5035
February      59751.2514
January       94924.8356
July         147238.0970
June         152718.6793
March        205005.4888
May          155028.8117
November     352461.0710
October      200322.9847
September    307649.9457
Name: Sales, dtype: float64

In [33]:
# Highest profit generated year
yearly_profit = clean_df.groupby("Year")["Sales"].sum()
yearly_profit

Year
2014    483966.1261
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64

In [34]:
yearly_profit.idxmax(),yearly_profit.max()

(2017, 733215.2552)

In [36]:
# which day has more orders
day_orders = clean_df.groupby("Day Name")["Sales"].sum()
day_orders

Day Name
Friday       427692.2593
Monday       428937.8157
Saturday     357984.6830
Sunday       385353.8464
Thursday     321965.7785
Tuesday      287209.5022
Wednesday     87775.6032
Name: Sales, dtype: float64

In [37]:
# which category generated the highest sales
category_sales = clean_df.groupby("Category")["Sales"].sum()
category_sales

Category
Furniture          741718.4233
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [38]:
category_sales.idxmax(),category_sales.max()

('Technology', 836154.033)

In [39]:
# region has highest sales
region_sales = clean_df.groupby(
    "Region"
)["Sales"].sum()

region_sales

Region
Central    501239.8908
East       678499.8680
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [40]:
region_sales.idxmax(), region_sales.max()

('West', 725457.8245)

MONTHLY SALES TRENDS

In [41]:
monthly_sales = clean_df.groupby(
     ["Year" , "Month"]
)["Sales"].sum()
monthly_sales

Year  Month
2014  1         14236.8950
      2          4519.8920
      3         55691.0090
      4         28013.9730
      5         23648.2870
      6         34595.1276
      7         33946.3930
      8         27909.4685
      9         81777.3508
      10        31453.3930
      11        78628.7167
      12        69545.6205
2015  1         18174.0756
      2         11951.4110
      3         38726.2520
      4         34195.2085
      5         30131.6865
      6         24797.2920
      7         28765.3250
      8         36898.3322
      9         64595.9180
      10        31404.9235
      11        75972.5635
      12        74919.5212
2016  1         18542.4910
      2         22978.8150
      3         51715.8750
      4         38750.0390
      5         56987.7280
      6         40344.5340
      7         39261.9630
      8         31115.3743
      9         73410.0249
      10        59687.7450
      11        79411.9658
      12        96999.0430
2017  1         43971.3740
      2         20301.1334
      3         58872.3528
      4         36521.5361
      5         44261.1102
      6         52981.7257
      7         45264.4160
      8         63120.8880
      9         87866.6520
      10        77776.9232
      11       118447.8250
      12        83829.3188
Name: Sales, dtype: float64

In [42]:
monthly_sales.idxmax(),monthly_sales.max()

((2017, 11), 118447.825)