## DAY 27 ADVANCED PANDAS II

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.shape

(180519, 31)

In [6]:
df[
     ["Sales" ,
      "Order Profit Per Order" ,
      "Customer Segment" ,
      "Market" ,
      "Late_delivery_risk",
      "Shipping Mode"]
].head()

,Sales,Order Profit Per Order,Customer Segment,Market,Late_delivery_risk,Shipping Mode
0,327.75,91.250000,Consumer,Pacific Asia,0,Standard Class
1,327.75,-249.089996,Consumer,Pacific Asia,1,Standard Class
2,327.75,-247.779999,Consumer,Pacific Asia,0,Standard Class
3,327.75,22.860001,Home Office,Pacific Asia,0,Standard Class
4,327.75,134.210007,Corporate,Pacific Asia,0,Standard Class

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Benefit per order           180519 non-null  float64
 1   Sales per customer          180519 non-null  float64
 2   Delivery Status             180519 non-null  object
 3   Late_delivery_risk          180519 non-null  int64
 4   Category Name               180519 non-null  object
 5   Customer City               180519 non-null  object
 6   Customer Country            180519 non-null  object
 7   Customer Fname              180519 non-null  object
 8   Customer Id                 180519 non-null  int64
 9   Customer Lname              180511 non-null  object
 10  Customer Segment            180519 non-null  object
 11  Customer State              180519 non-null  object
 12  Department Name             180519 non-null  object
 13  Market                      180519 non-null  object
 14  Order Country               180519 non-null  object
 15  order date (DateOrders)     180519 non-null  object
 16  Order Id                    180519 non-null  int64
 17  Order Item Discount         180519 non-null  float64
 18  Order Item Discount Rate    180519 non-null  float64
 19  Order Item Product Price    180519 non-null  float64
 20  Order Item Profit Ratio     180519 non-null  float64
 21  Order Item Quantity         180519 non-null  int64
 22  Sales                       180519 non-null  float64
 23  Order Item Total            180519 non-null  float64
 24  Order Profit Per Order      180519 non-null  float64
 25  Order Region                180519 non-null  object
 26  Order State                 180519 non-null  object
 27  Order Status                180519 non-null  object
 28  Product Name                180519 non-null  object
 29  shipping date (DateOrders)  180519 non-null  object
 30  Shipping Mode               180519 non-null  object
dtypes: float64(9), int64(4), object(18)
memory usage: 42.7+ MB

### apply()

In [11]:
def classify_profit(profit):
     if profit > 100:
          return "Highly Profitable"
     elif profit > 0:
          return "Profitable"
     else:
          return "Loss Making"

df["Profit_Category"] = df["Order Profit Per Order"].apply(
     classify_profit
)
df[[
    "Order Profit Per Order",
    "Profit_Category"
]].head(10)

   Order Profit Per Order    Profit_Category
0               91.250000         Profitable
1             -249.089996        Loss Making
2             -247.779999        Loss Making
3               22.860001         Profitable
4              134.210007  Highly Profitable
5               18.580000         Profitable
6               95.180000         Profitable
7               68.430000         Profitable
8              133.720001  Highly Profitable
9              132.149994  Highly Profitable

In [12]:
df["Profit_Category"].value_counts()

Profit_Category
Profitable           125248
Loss Making           34961
Highly Profitable     20310
Name: count, dtype: int64

### map()

In [16]:
df["Delivery_Risk_Status"] = df["Late_delivery_risk"].map(
     {
          0:"No Risk" ,
          1:"Late Risk"
     }
)
df[[
     "Late_delivery_risk",
     "Delivery_Risk_Status"
]].head(10)

   Late_delivery_risk Delivery_Risk_Status
0                   0              No Risk
1                   1            Late Risk
2                   0              No Risk
3                   0              No Risk
4                   0              No Risk
5                   0              No Risk
6                   1            Late Risk
7                   1            Late Risk
8                   1            Late Risk
9                   1            Late Risk

In [17]:
df["Delivery_Risk_Status"].value_counts()

Delivery_Risk_Status
Late Risk    98977
No Risk      81542
Name: count, dtype: int64