## DAY 27 ADVANCED PANDAS II

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Data_Co_Supply_Chain_Dataset.csv" , encoding="latin1")
df.shape

(180519, 31)

In [6]:
df[
     ["Sales" ,
      "Order Profit Per Order" ,
      "Customer Segment" ,
      "Market" ,
      "Late_delivery_risk",
      "Shipping Mode"]
].head()

,Sales,Order Profit Per Order,Customer Segment,Market,Late_delivery_risk,Shipping Mode
0,327.75,91.250000,Consumer,Pacific Asia,0,Standard Class
1,327.75,-249.089996,Consumer,Pacific Asia,1,Standard Class
2,327.75,-247.779999,Consumer,Pacific Asia,0,Standard Class
3,327.75,22.860001,Home Office,Pacific Asia,0,Standard Class
4,327.75,134.210007,Corporate,Pacific Asia,0,Standard Class

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Benefit per order           180519 non-null  float64
 1   Sales per customer          180519 non-null  float64
 2   Delivery Status             180519 non-null  object
 3   Late_delivery_risk          180519 non-null  int64
 4   Category Name               180519 non-null  object
 5   Customer City               180519 non-null  object
 6   Customer Country            180519 non-null  object
 7   Customer Fname              180519 non-null  object
 8   Customer Id                 180519 non-null  int64
 9   Customer Lname              180511 non-null  object
 10  Customer Segment            180519 non-null  object
 11  Customer State              180519 non-null  object
 12  Department Name             180519 non-null  object
 13  Market                      180519 non-null  object
 14  Order Country               180519 non-null  object
 15  order date (DateOrders)     180519 non-null  object
 16  Order Id                    180519 non-null  int64
 17  Order Item Discount         180519 non-null  float64
 18  Order Item Discount Rate    180519 non-null  float64
 19  Order Item Product Price    180519 non-null  float64
 20  Order Item Profit Ratio     180519 non-null  float64
 21  Order Item Quantity         180519 non-null  int64
 22  Sales                       180519 non-null  float64
 23  Order Item Total            180519 non-null  float64
 24  Order Profit Per Order      180519 non-null  float64
 25  Order Region                180519 non-null  object
 26  Order State                 180519 non-null  object
 27  Order Status                180519 non-null  object
 28  Product Name                180519 non-null  object
 29  shipping date (DateOrders)  180519 non-null  object
 30  Shipping Mode               180519 non-null  object
dtypes: float64(9), int64(4), object(18)
memory usage: 42.7+ MB

### apply()

In [11]:
def classify_profit(profit):
     if profit > 100:
          return "Highly Profitable"
     elif profit > 0:
          return "Profitable"
     else:
          return "Loss Making"

df["Profit_Category"] = df["Order Profit Per Order"].apply(
     classify_profit
)
df[[
    "Order Profit Per Order",
    "Profit_Category"
]].head(10)

   Order Profit Per Order    Profit_Category
0               91.250000         Profitable
1             -249.089996        Loss Making
2             -247.779999        Loss Making
3               22.860001         Profitable
4              134.210007  Highly Profitable
5               18.580000         Profitable
6               95.180000         Profitable
7               68.430000         Profitable
8              133.720001  Highly Profitable
9              132.149994  Highly Profitable

In [12]:
df["Profit_Category"].value_counts()

Profit_Category
Profitable           125248
Loss Making           34961
Highly Profitable     20310
Name: count, dtype: int64

### map()

In [16]:
df["Delivery_Risk_Status"] = df["Late_delivery_risk"].map(
     {
          0:"No Risk" ,
          1:"Late Risk"
     }
)
df[[
     "Late_delivery_risk",
     "Delivery_Risk_Status"
]].head(10)

   Late_delivery_risk Delivery_Risk_Status
0                   0              No Risk
1                   1            Late Risk
2                   0              No Risk
3                   0              No Risk
4                   0              No Risk
5                   0              No Risk
6                   1            Late Risk
7                   1            Late Risk
8                   1            Late Risk
9                   1            Late Risk

In [17]:
df["Delivery_Risk_Status"].value_counts()

Delivery_Risk_Status
Late Risk    98977
No Risk      81542
Name: count, dtype: int64

### replace(), where(), query()

### 1) replace()

In [18]:
df["Customer Segment"].value_counts()

Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [21]:
df["Customer_Segment_Standard"] = df["Customer Segment"].replace({
    "Consumer": "B2C",
    "Corporate": "B2B",
    "Home Office": "Home Office"
})
df["Customer_Segment_Standard"].value_counts()

Customer_Segment_Standard
B2C            93504
B2B            54789
Home Office    32226
Name: count, dtype: int64

### 2) where()

In [23]:
df["Profit_Positive"] = df["Order Profit Per Order"].where(
    df["Order Profit Per Order"] > 0,
    0
)
df[[
    "Order Profit Per Order",
    "Profit_Positive"
]].head(10)

   Order Profit Per Order  Profit_Positive
0               91.250000        91.250000
1             -249.089996         0.000000
2             -247.779999         0.000000
3               22.860001        22.860001
4              134.210007       134.210007
5               18.580000        18.580000
6               95.180000        95.180000
7               68.430000        68.430000
8              133.720001       133.720001
9              132.149994       132.149994

### 3) query()

In [24]:
high_value_orders = df.query(
    "Sales > 1000 and `Order Profit Per Order` > 100"
)

high_value_orders.head()

,Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,...,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,Profit_Category,Delivery_Risk_Status,Customer_Segment_Standard,Profit_Positive
152,595.349976,1417.5,Late delivery,1,Computers,Caguas,Puerto Rico,Alma,14287,Delgado,...,Northern Europe,Inglaterra,COMPLETE,Dell Laptop,11-03-2017 12:55,Second Class,Highly Profitable,Late Risk,B2C,595.349976
1370,599.250000,1275.0,Advance shipping,0,Computers,Caguas,Puerto Rico,Jamalia,14299,Ortega,...,Southern Europe,Madrid,PENDING_PAYMENT,Dell Laptop,10/31/2017 17:07,Standard Class,Highly Profitable,No Risk,Home Office,599.250000
1375,410.850006,1245.0,Late delivery,1,Computers,Caguas,Puerto Rico,Patience,14297,Ellis,...,Western Europe,Utrecht,PENDING_PAYMENT,Dell Laptop,11-03-2017 16:25,Standard Class,Highly Profitable,Late Risk,Home Office,410.850006
1594,281.250000,1125.0,Late delivery,1,Computers,Caguas,Puerto Rico,Denise,14348,Mosley,...,Western Europe,Viena,ON_HOLD,Dell Laptop,11-05-2017 10:17,Second Class,Highly Profitable,Late Risk,B2C,281.250000
3204,382.730011,1417.5,Late delivery,1,Computers,Caguas,Puerto Rico,Reagan,18077,Daniels,...,Southeast Asia,Bangkok,PENDING_PAYMENT,Dell Laptop,12/28/2017 20:43,Standard Class,Highly Profitable,Late Risk,Home Office,382.730011

In [25]:
high_value_orders.shape

(346, 35)

In [26]:
high_value_orders["Sales"].sum()

523999.89989999996