In [1]:
import pandas as pd
print(pd.__version__)

2.2.0

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_5060\1804728916.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
import pandas as pd

SERIES

In [30]:
employee_salary = pd.Series(
     [50000 , 65000 , 70000 , 55000],
     index=["Rahul","Priya", "Amit" , "Sneha"])

employee_salary

Rahul    50000
Priya    65000
Amit     70000
Sneha    55000
dtype: int64

DATAFRAMES

In [27]:
employee_analysis = {
     "Employee":['Rahul' , 'Priya' , 'Amit' , 'Sneha'],
     "Department":['Sales' , 'HR' , 'IT' , 'Finance'],
     "Experience":[3 , 5 , 4 , 2]
}

employee_df = pd.DataFrame(employee_analysis)

employee_df

  Employee Department  Experience
0    Rahul      Sales           3
1    Priya         HR           5
2     Amit         IT           4
3    Sneha    Finance           2

In [ ]:
product_details = {
     "Product":['Laptop' , 'Mouse' , 'Keyboard' , 'Monitor'],
     "Price":[85000 , 1200 , 2500 , 18000],
     "Stock":[12 , 150 , 80 , 25]
}

product_df = pd.DataFrame(product_details)

product_df

    Product  Price  Stock
0    Laptop  85000     12
1     Mouse   1200    150
2  Keyboard   2500     80
3   Monitor  18000     25

READING CSV FILES

In [44]:
employee_df = pd.read_csv("employee.csv")
employee_df

  Employee Department  Salary
0    Rahul      Sales   50000
1    Priya         HR   65000
2     Amit         IT   70000
3    Sneha    Finance   55000

EXPLORING DATA FROM CSV

In [51]:
employee_df = pd.read_csv("employee.csv")

employee_df.head()
employee_df.head(2)
employee_df.tail()
employee_df.tail(2)
employee_df.info()
employee_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    4 non-null      object
 1   Department  4 non-null      object
 2   Salary      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

             Salary
count      4.000000
mean   60000.000000
std     9128.709292
min    50000.000000
25%    53750.000000
50%    60000.000000
75%    66250.000000
max    70000.000000

SELECTING COLUMNS

In [58]:
employee_df = pd.read_csv("employee.csv")

employee_df["Salary"]

employee_df["Department"]

employee_df[["Employee", "Salary"]]

employee_df[["Salary" , "Department"]]

   Salary Department
0   50000      Sales
1   65000         HR
2   70000         IT
3   55000    Finance